blank_issues_enabled: true
contact_links:
  - name: Genji Ball Ranked Discord
    url: https://discord.gg/sv9VVjh5pT
    about: For questions about ranked, the leaderboard and hosting ranked lobbies.
